# Generated by Django 3.2.7 on 2023-05-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230525_1022'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_movies',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='movies.Movie'),
        ),
    ]
